name: fixer_app
description: A new Flutter project.

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutterflow_ui: 0.2.0+1
  flutter_spinkit: ^5.2.0
  adaptive_theme: ^3.5.0
  shared_preferences: 2.2.2
  dio: ^5.4.1
  bloc: ^8.1.3
  flutter_bloc: ^8.1.4
  conditional_builder_null_safety: ^0.0.6
  fluttertoast: ^8.2.4
  http: ^0.13.6







dev_dependencies:
  flutter_launcher_icons: 0.13.1
  flutter_lints: 3.0.0
  image: 4.0.17
  lints: 3.0.0
  icons_launcher: ^2.1.3

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/

icons_launcher:
  image_path: "assets/images/android_app_icon.png"
  platforms:
    android:
      enable: true
      adaptive_background_color: "#FFEEDD"
      adaptive_foreground_image: "assets/images/android_app_icon.png"
    ios:
      enable: true
      image_path: "assets/images/apple_app_Icon.png"
